app = "euros-backend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ["app"]

[metrics]
  path = "/metrics"
  port = 9091

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "15s"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "30s"
    timeout = "15s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
