# fly.toml app configuration file generated for euros-backend on 2024-05-28T16:04:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'euros-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
